### ISSUE TITLE
Duplicate Joyce Axe

### ISSUE THREAD

**Issue by HeroicSwordsman** [jpw1991/chebs-mythical-weapons#5]
Thanks for taking the time to report a bug. Please fill in the template below and delete any irrelevant parts.

# Description

Killing the minotaur drops 2 axes.  Modlist matches the server.

**Comment by jpw1991** [comment]
It's probably dropping a copy of the axe per player online. I thought I switched that off, but I'll double check. Thank you

**Comment by jpw1991** [comment]
![image](https://github.com/jpw1991/chebs-mythical-weapons/assets/13718599/5352d547-3b77-4884-8b32-568209da0da3)

Ugh, the plot thickens. Gonna have to research why it drops twice at all

**Comment by HeroicSwordsman** [comment]
Might just be how CLLC interacts with drop rates?

**Comment by alundil** [comment]
Killed the minotaur (which had no name) and I got dozens of the "Joyce Axe"
![valheim_J2CBNZmzfm](https://github.com/jpw1991/chebs-mythical-weapons/assets/29282515/7c5d6e85-ff04-4daf-b8cb-5698df129e06)
![valheim_cPP2FpOqYr](https://github.com/jpw1991/chebs-mythical-weapons/assets/29282515/5f4f6e44-005a-4cbb-8e83-1e1d895820f7)

**Comment by jpw1991** [comment]
@alundil were you playing alone?

**Comment by alundil** [comment]
I was playing alone, yes. Was in my hosted/dedicated server that I share
with my wife. But it was just me at the time.

**Comment by jpw1991** [comment]
@alundil  it's probably some other mod interacting with mine to cause this outcome.

To help properly I need logs and configs because it works just fine on my end

**Comment by alundil** [comment]
Understood. What, specifically, logs and configs would you like to see?

**Comment by alundil** [comment]
Ok so I found another Minotaur while exploring today.
![valheim_TbWzckctAj](https://github.com/jpw1991/chebs-mythical-weapons/assets/29282515/f2828bfa-0cba-4352-bb23-78963767eb31)
I used the console "killenemies" command. And this was the result.
![valheim_7Zf48PgZwg](https://github.com/jpw1991/chebs-mythical-weapons/assets/29282515/e3d94e34-bc23-4653-ab79-073f97181579)

There were no errors that I saw while that Minotaur died/spawned loot.

That is the logout.log for the current session on
[LogOutput.log](https://github.com/jpw1991/chebs-mythical-weapons/files/12197682/LogOutput.log)

**Comment by alundil** [comment]
If there's something else you would like me to try/provide let me and I'll try and accommodate.

**Comment by jpw1991** [comment]
Yeah this is not related to my mod at all. Remember that if you use mods like CLLC that go and change the drops, of course there will be 10 axes getting dropped if you configure CLLC with a drop multiplier of 10 etc.

**Comment by alundil** [comment]
my CLLC drop modifier settings are unmodified (ie not configured for any extra drops of any type) with the exception of "Loot System to be used" set to "CalculateAmount" which is defined as "Calculate amount: A boar has a 50% chance to drop 2 meat, it will always drop 1."

![image](https://github.com/jpw1991/chebs-mythical-weapons/assets/29282515/03cb8b91-bb1f-4ef2-bd85-c93d20918e0c)

[org.bepinex.plugins.creaturelevelcontrol.txt](https://github.com/jpw1991/chebs-mythical-weapons/files/12490999/org.bepinex.plugins.creaturelevelcontrol.txt)

Shame that this is now closed, though.

**Comment by jpw1991** [comment]
If you test the mod in isolation, it will only drop one axe. Therefore some other mod is causing this

**Comment by jpw1991** [comment]
@alundil if you find out which mod is causing this and tell me why, I will think about some kind of compatibility fix. Until then though, this can stay closed
