### ISSUE TITLE
Mintymintos & Shawesome feedback

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/chebs-mythical-weapons#7]
# Feedback

## Mintymintos

- Bow of Apollo
  - Hi Cheb, we need a little arrow drop on the bow. it's nearly impossible to hit anything now
- Blade of Olympus
  - Can you increase the stats as it's the same as the one handed excalibur
  - I’d say 140 to start and increase by 25 each time
  - It needs to be better at blocking
  - Could you take off some of the effects please
- Minotaur
  - Add map icon

## Shawesome

- Wants a 1h version of the sword for dual wielding via a different mod

# Implementation

- Bow of Apollo
  - Change true/false entry for gravity adjustment to be a tweakable value
- Blade of Olympus
  - Increase base stats to start at 140, then increase by 25 each time
  - Increase blocking (double it, I guess)
  - Add config option to disable some of the particle effects
  - Add a 1h version of the sword:
    - Rename existing 2h sword to Greatsword of Olympus
    - Add 1h variant called Blade of Olympus with stats similar to Excalibur, but lightning damage instead of spirit

**Comment by Shawesome4u** [comment]
Thank you sir! the character is using 1 hand to hold however dual wielding is not possible, i believe because the description still shows the 1h variant as a 2h weapon.

**Comment by jpw1991** [comment]
Thanks @Shawesome4u I'll investigate

**Comment by jpw1991** [comment]
fixed in new version
